global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'langgraph-orchestrator'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Application metrics
  - job_name: 'langgraph-app'
    static_configs:
      - targets: ['langgraph_app:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics endpoint
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['langgraph_app:8000']
    scrape_interval: 15s
    metrics_path: /custom-metrics
    params:
      format: ['prometheus']

# Remote write configuration (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"